# docker-compose.yml
version: '3.7'

services:
  writing_app:
    build:
      context: .
      dockerfile: Dockerfile.writing
    environment:
      # set database, memcached etc credentials
      DB_HOST: mysql
      DB_NAME: flask
      DB_USER: test
      DB_PASSWORD: test
    ports:
      - "5000:5000"
    depends_on:
      - mysql

  reading_app:
    build:
      context: .
      dockerfile: Dockerfile.reading
    environment:
      # set database, memcached etc credentials
      DB_HOST: mysql
      DB_NAME: flask
      DB_USER: test
      DB_PASSWORD: test
    ports:
      - "5001:5001"
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: flask
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - "3306:3306"

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin:latest
    container_name: flask_phpmyadmin
    restart: unless-stopped
    labels:
      project: "flask"
      day: "9 Sep 2019"
    ports:
      - "5010:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: test
      PMA_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
