# Dockerfile.reading

FROM python:3.7.4-alpine3.10

# Install system dependencies
RUN apk add --no-cache --virtual .build-deps g++ python3-dev libffi-dev openssl-dev && \
    apk add --no-cache --update python3 && \
    pip3 install --upgrade pip setuptools
RUN pip3 install pendulum service_identity

WORKDIR /app

RUN pip install PyMySQL
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY . .

EXPOSE 5001

CMD ["python", "reading_app.py"]
